### ISSUE TITLE
Novas does not support Windows10 system 

### ISSUE THREAD

**Issue by yangyang-studio** [brandon-rhodes/python-novas#15] opened 2021-11-30 16:18 UTC
![16382889562167277148561125798447](https://user-images.githubusercontent.com/84533790/144085285-999a64ac-5831-40cf-b3c7-591465487430.jpg)
With pip install novas, the system prompts that the operating system is not supported.

**Comment by brandon-rhodes** [comment] 2021-11-30 19:30
Yes, that is correct, the packaging does not support Windows.

I am not aware that the Naval Observatory has any more plans to develop or improve this software — the web site that described it went offline more than a year ago — so as far as I know no further development is planned on this library.

But, do you know anyone who would be interested in volunteering to port it to Windows and get it compiling with Python?

**Comment by wvenialbo** [comment] 2022-09-09 22:32
> ...
> But, do you know anyone who would be interested in volunteering to port it to Windows and get it compiling with Python?

If you give me guidance on how I can help (just a brief description of what is needed), I can spare some time and be more than happy to contribute.

Python is not my daily programming language but I have experience with it. On the other hand, I already have experience with NOVAS since the 1990s because I developed the software used to produce the data for the Paraguayan Astronomical Almanac. However, my configuration is as follows:

```
C++ almanac generator -> NOVAS C++ adapter (inline headers only)
                      -> NOVAS C-FORTRAN wrapper (prototype headers only)
                      -> NOVAS FORTRAN (DLL binary)
                      -> JPLEPHEM FORTRAN (DLL binary)
```

An edition of the almanac, issued to commemorate the bicentennial of my country's independence, is available online in digital format at Google Books (free of charge), if you wish to consult it: https://goo.gl/uPfQz2

**Comment by brandon-rhodes** [comment] 2022-09-09 23:00
@wvenialbo — I am not sure whether @yangyang-studio will answer or not. I would presume the first step would be to try removing the `raise OSError…` line (or commenting it out) and then see what happens on Windows 10 if the compilation goes ahead and is attempted. Maybe the few problems that come up will be surmountable? But maybe not; maybe the whole codebase would have problems with Windows.

Thanks for the link to the book—I didn't know that Paraguay had its own almanac, and I am impressed with how much information, how many chapters and diagrams and tables, it contains!

**Comment by wvenialbo** [comment] 2022-09-10 23:33
I'll fork it and give it a try. Probably the code should be patched somehow due to specific system calls or Microsoft compiler "safe version" function requirements; I remember I should do the latter in another project some time ago.

Anyway, now there is Windows Subsystem for Linux for the impatient user to use the code as is. There is also Clang support in Visual Studio, but if the issue is operating system specific, the code must be patched as well.

**Comment by brandon-rhodes** [comment] 2024-04-27 12:28
I'm going to close this as won't-fix for right now, since upstream has not announced any plans to support Windows. If anyone gets something working and wants to share their branch, though, please feel free to open a pull request for consideration. But I'm not likely to merge anything that goes beyond a simple couple of fixes ­— a major rewrite would make it hard for me to merge new code from upstream, if they ever activate again.

**Closed by brandon-rhodes** 2024-04-27 12:28 UTC
